name: Test macOS Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-macos-intel:
    runs-on: macos-13  # Intel-based runner
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt found"
        pip install pyinstaller pillow matplotlib numpy tkinter || true
    
    - name: Test basic imports
      run: |
        python -c "
        try:
            import tkinter as tk
            print('✅ tkinter import OK')
            root = tk.Tk()
            root.withdraw()
            print('✅ tkinter window creation OK')
            root.destroy()
        except Exception as e:
            print(f'❌ tkinter error: {e}')
            
        try:
            from PIL import Image
            print('✅ PIL import OK')
        except Exception as e:
            print(f'❌ PIL error: {e}')
            
        try:
            import matplotlib.pyplot as plt
            print('✅ matplotlib import OK')
        except Exception as e:
            print(f'❌ matplotlib error: {e}')
        "
    
    - name: Test app startup
      run: |
        timeout 30s python stampz.py --test 2>&1 || echo "App test completed or timed out"
    
    - name: Create test bundle
      run: |
        pyinstaller --onedir --windowed \
          --add-data "data:data" \
          --add-data "templates:templates" \
          --hidden-import="PIL._tkinter_finder" \
          --collect-all="matplotlib" \
          --collect-all="PIL" \
          stampz.py
    
    - name: Test bundle execution
      run: |
        echo "Testing bundle startup..."
        cd dist/stampz
        timeout 10s ./stampz --version 2>&1 || echo "Bundle test completed or timed out"
        ls -la
        file stampz
    
    - name: Upload test bundle
      uses: actions/upload-artifact@v3
      with:
        name: test-bundle-intel-macos
        path: dist/stampz/
        retention-days: 7

  test-macos-arm:
    runs-on: macos-latest  # ARM-based runner (M1/M2)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt found"
        pip install pyinstaller pillow matplotlib numpy tkinter || true
    
    - name: Test basic imports
      run: |
        python -c "
        try:
            import tkinter as tk
            print('✅ tkinter import OK')
            root = tk.Tk()
            root.withdraw()
            print('✅ tkinter window creation OK')
            root.destroy()
        except Exception as e:
            print(f'❌ tkinter error: {e}')
        "
    
    - name: Test app startup
      run: |
        timeout 30s python stampz.py --test 2>&1 || echo "App test completed or timed out"
    
    - name: Create test bundle (ARM)
      run: |
        pyinstaller --onedir --windowed \
          --add-data "data:data" \
          --add-data "templates:templates" \
          --hidden-import="PIL._tkinter_finder" \
          --collect-all="matplotlib" \
          --collect-all="PIL" \
          --target-arch=arm64 \
          stampz.py
    
    - name: Upload test bundle (ARM)
      uses: actions/upload-artifact@v3
      with:
        name: test-bundle-arm-macos
        path: dist/stampz/
        retention-days: 7