name: Test Cross-Platform Bundles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-bundle:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install optional tifffile for 16-bit TIFF support
        pip install tifffile
        pip list
    
    - name: Test basic imports
      run: |
        python -c "
        try:
            import tkinter as tk
            print('✅ tkinter import OK')
            root = tk.Tk()
            root.withdraw()
            print('✅ tkinter window creation OK')
            root.destroy()
        except Exception as e:
            print(f'❌ tkinter error: {e}')
            
        try:
            from PIL import Image
            print('✅ PIL import OK')
        except Exception as e:
            print(f'❌ PIL error: {e}')
            
        try:
            import matplotlib.pyplot as plt
            print('✅ matplotlib import OK')
        except Exception as e:
            print(f'❌ matplotlib error: {e}')
        "
    
    - name: Test app import
      run: |
        python -c "import main; print('✅ main.py import OK')" || echo "Import test completed"
      timeout-minutes: 2
    
    - name: Create self-contained Windows bundle
      run: |
        # Use our proper spec file for consistent builds
        pyinstaller --clean stampz.spec
    
    - name: Test bundle execution
      run: |
        echo "Testing Windows bundle startup..."
        cd dist
        dir
        # Check for our actual executable name
        if (Test-Path "StampZ-III.exe") {
          echo "✅ StampZ-III.exe exists"
          $size = (Get-Item "StampZ-III.exe").length
          echo "Executable size: $size bytes"
          if ($size -gt 10MB) {
            echo "✅ Executable size looks reasonable"
          }
        } else {
          echo "❌ StampZ-III.exe not found"
          echo "Available files:"
          dir
        }
    
    - name: Check bundle dependencies
      run: |
        cd dist
        echo "Checking Windows bundle (onefile)..."
        dir
        if (Test-Path "StampZ-III.exe") {
          echo "Bundle created successfully as single executable"
          $size = (Get-Item "StampZ-III.exe").length
          echo "Final executable size: $([math]::Round($size/1MB, 2)) MB"
        }
    
    - name: Upload Windows bundle
      uses: actions/upload-artifact@v4
      with:
        name: test-bundle-windows-x64
        path: dist/
        retention-days: 7

